# Generated by Django 4.2.2 on 2024-07-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_gaminglaptop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopPriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=100)),
                ('desired_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
