# Generated by Django 4.2.2 on 2024-07-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_laptoppricealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaminglaptop',
            name='Name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laptoppricealert',
            name='laptop_name',
            field=models.TextField(),
        ),
    ]
