# Generated by Django 4.2.2 on 2024-07-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_gaminglaptop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaminglaptop',
            name='Name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='laptoppricealert',
            name='laptop_name',
            field=models.CharField(),
        ),
    ]
